PythonVersion="3.8.6"
packagedir=".python_packages/lib/site-packages"
OperationId="|1+S/6vHhaUI=.df06ee55_"
SourceDirectoryInBuildContainer="/tmp/8d8a58b915e21da"
PlatformName="python"
CompressDestinationDir="false"
